### PR TITLE
Allow linking a user to a channel by their ID, useful for when the fi…

### PR DESCRIPTION
**Pull request by mitchcapper**
…rst result is not your friend and they don't have a vanity handle

### CODE REVIEW

**Review by Weetbix — CHANGES_REQUESTED** [review]
I think this is best put into 2 more util functions: `findFriendUserByID` and `findFriendUser`

`findFriendUser` being responsible for testing if its an ID or not and calling the appropriate function.

**Comment by mitchcapper** [comment]
No problem. Most of the code is shared so would it make sense to have a findFriendUser(string)  that if string is not an ID it calls getUserIDByName to get the ID,  then have findFriendUser continue with most of the remaining code path from findFriendUserByName?

**Comment by Weetbix** [comment]
Yeah that sounds good too

**Comment by mitchcapper** [comment]
Ok refactoring submitted.

**Pull request merged**
